version: "3.1"
services:
  postgres-dev:
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: schema
      POSTGRES_USER: schema
      POSTGRES_PASSWORD: schema
